[project]
name = "soupson"
version = "0.1.0"
description = "Pretty-print HTML/XML from the command line"
readme = "README.md"
authors = [
    { name = "Mike Clark", email = "mike.clark.8192@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.14.2",  # For UnicodeDammit encoding detection
    "lxml>=6.0.2",
    "cssselect>=1.2.0",
]


[project.scripts]
soupson = "soupson:main"

[project.optional-dependencies]
dev = [
    "pytest>=8.0.0",
]

[build-system]
requires = ["uv_build>=0.9.7,<0.10.0"]
build-backend = "uv_build"
