[project]
name = "soupson"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mike Clark", email = "mike.clark.8192@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.14.2",
]


[project.scripts]
soupson = "soupson:main"

[project.optional-dependencies]
lxml = [
    "lxml>=6.0.2",
]
html5lib = [
    "html5lib>=1.1",
]
all = [
    "html5lib>=1.1",
    "lxml>=6.0.2",
]
dev = [
    "pytest>=8.0.0",
    "lxml>=6.0.2",
]

[build-system]
requires = ["uv_build>=0.9.7,<0.10.0"]
build-backend = "uv_build"
